### ISSUE TITLE
the repository list seems to be outdated

### ISSUE THREAD

**Issue by hubadubdubdub** [nemal34/beyondthehorizon_wj#1]
Hi, I've run into an issue while trying to download the list with WJ. I could not progress any further than rootbuilder.4.4.1.zip because it is not available anymore at that location on gihub. The plugin progressed further and folder structures have changed and files have been moved / archived.

Could you update your list in case there are more files affected? I could modify the repository list myself by seeking out the individual mods and plugins and add them to the list, but I am not familiar with the editing of the WJ files at all.

**Comment by matt-gough** [comment]
Yeah, experiencing the same here.

Closest currently hosted version of rootbuilder is at this link (clicking this link directly downloads the file):[https://github.com/Kezyma/ModOrganizer-Plugins/releases/download/rootbuilder/rootbuilder.4.5.2.zip](https://github.com/Kezyma/ModOrganizer-Plugins/releases/download/rootbuilder/rootbuilder.4.5.2.zip)

I'm not sure published Wabbajack lists are modifiable, but if they were one could just replace the dependency on 4.4.1 with 4.5.2 and pray it works.

I tried downloading the file 4.5.2 directly, dropping it into the downloads folder, and then renaming it to rootbuilder.4.4.1.zip to see if it would accept that as a valid file. Sadly, the computer has outsmarted me, and this does not work; it still tries to download the old version.

**Comment by nemal34** [comment]
The WJ download issue is fixed in the new official modlist.
Bth will also get this fix when it's updated.
