### ISSUE TITLE
Unable to Download Rootbuilder

### ISSUE THREAD

**Issue by Jackylegssss** [nemal34/beyondthehorizon_wj#2]
Installation was going fine until the final step which appears to be downloading and installing rootbuilder; got this error at the end along with the "Install Failed" prompt: _Unable to download rootbuilder.4.4.1.zip (HTTPDownloader+State|https://github.com/Kezyma/ModOrganizer-Plugins/releases/download/rootbuilder/rootbuilder.4.4.1.zip)_

Would wiping Fallout 4 and re-trying the Wabbajack download help?

[Wabbajack.current.log](https://github.com/nemal34/beyondthehorizon_wj/files/15081233/Wabbajack.current.log)

**Comment by matt-gough** [comment]
This is a duplicate of [https://github.com/nemal34/beyondthehorizon_wj/issues/1](https://github.com/nemal34/beyondthehorizon_wj/issues/1)

Sadly, I don't think reinstalling anything is going to help you here. It's a problem with the Wabbajack list as far as I can see.
